export type SettingFieldType = "text" | "textarea" | "email" | "tel" | "facebook" | "youtube" | "image";

export type SettingField = {
  key: string;
  label: string;
  help?: string;
  type: SettingFieldType;
  maxLength: number;
  lang?: string;
};

export type SettingGroup = { title: string; fields: readonly SettingField[] };

export const settingGroups: readonly SettingGroup[] = [
  {
    title: "Home page",
    fields: [
      {
        key: "home_banner",
        label: "Home page banner image",
        help: "Choose one large image. It is resized automatically.",
        type: "image",
        maxLength: 200,
      },
      {
        key: "site_tagline",
        label: "Tagline",
        help: "Short motto shown on the website. Write it in Tamil.",
        type: "text",
        maxLength: 120,
        lang: "ta",
      },
      {
        key: "home_headline",
        label: "Home page headline",
        help: "Write it in Tamil.",
        type: "text",
        maxLength: 160,
        lang: "ta",
      },
      {
        key: "home_welcome",
        label: "Welcome text",
        help: "Write it in Tamil.",
        type: "textarea",
        maxLength: 600,
        lang: "ta",
      },
    ],
  },
  {
    title: "Bank details (for donations)",
    fields: [
      { key: "bank_name", label: "Bank name", type: "text", maxLength: 100 },
      { key: "bank_branch", label: "Branch", type: "text", maxLength: 100 },
      { key: "bank_account_name", label: "Account name", type: "text", maxLength: 120 },
      { key: "bank_account_number", label: "Account number", type: "text", maxLength: 40 },
      {
        key: "bank_note",
        label: "Additional note",
        help: "Shown on the Donation page.",
        type: "textarea",
        maxLength: 500,
      },
    ],
  },
  {
    title: "Contact details",
    fields: [
      { key: "contact_phone", label: "Phone number", type: "tel", maxLength: 40 },
      { key: "contact_email", label: "Email address", type: "email", maxLength: 120 },
      { key: "contact_address", label: "Address", type: "textarea", maxLength: 300 },
    ],
  },
  {
    title: "Social media",
    fields: [
      {
        key: "facebook_url",
        label: "Facebook page link",
        help: "Example: https://www.facebook.com/yourpage",
        type: "facebook",
        maxLength: 200,
      },
      {
        key: "youtube_url",
        label: "YouTube channel link",
        help: "Example: https://www.youtube.com/@yourchannel",
        type: "youtube",
        maxLength: 200,
      },
    ],
  },
];

export const categoryEnglish: Record<string, string> = {
  social: "Social Service",
  green: "Green Homeland",
  arts: "Arts & Literature",
  reading: "Reading (Vaasippom Suvaasippom)",
};

export const roleGroupEnglish: Record<string, string> = {
  director: "Director",
  president: "President",
  secretary: "Secretary",
  treasurer: "Treasurer",
  member: "Members",
  patron: "Patrons",
};

export const admin = {
  title: "Admin Panel",
  login: {
    title: "Admin Login",
    username: "Username",
    password: "Password",
    submit: "Log in",
    pending: "Logging in…",
    invalid: "Incorrect username or password.",
    blocked: "Too many failed attempts. Please wait a while and try again.",
    required: "Please enter your username and password.",
    failed: "Could not log in. Please try again.",
    backToSite: "Back to the website",
  },
  nav: {
    dashboard: "Dashboard",
    posts: "Posts",
    team: "Committee",
    settings: "Settings",
    viewSite: "View website",
    logout: "Log out",
  },
  dashboard: {
    title: "Welcome",
    intro: "Manage the website content from here.",
    cards: {
      posts: {
        title: "Posts",
        text: "Add news and updates for the four categories.",
      },
      team: {
        title: "Executive Committee",
        text: "Manage committee members' details and photos.",
      },
      settings: {
        title: "Settings",
        text: "Bank details, contact details, social media links and the home page texts.",
      },
    },
  },
  common: {
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    back: "Back",
    saving: "Saving…",
    required: "This field is required.",
    tooLong: (n: number) => `Maximum ${n} characters allowed.`,
    noticeCreated: "Created successfully.",
    noticeSaved: "Changes saved.",
    noticeDeleted: "Deleted successfully.",
    actionFailed: "Something went wrong. Please try again.",
    fixErrors: "Please fix the highlighted errors and try again.",
  },
  posts: {
    title: "Posts",
    newPost: "New post",
    editPost: "Edit post",
    empty: "No posts found.",
    columns: { post: "Post", category: "Category", status: "Status", date: "Date", actions: "Actions" },
    published: "Published",
    draft: "Draft",
    view: "View",
    publish: "Publish",
    unpublish: "Unpublish",
    confirmDelete: "Delete this post permanently? This cannot be undone.",
    allCategories: "All categories",
    allStatuses: "All statuses",
    filter: "Filter",
    previous: "Previous",
    next: "Next",
    page: (page: number, pages: number) => `Page ${page} of ${pages}`,
    photoCount: (n: number) => `${n} photo${n === 1 ? "" : "s"}`,
    hasVideo: "Video",
    hasFacebook: "Facebook link",
    noText: "(no text)",
    composer: {
      postingTo: "Posting to",
      chooseCategory: "Choose category",
      placeholder: "What's new? Write your news here (in Tamil)…",
      addToPost: "Add to your post",
      photos: "Photos",
      video: "YouTube video",
      facebook: "Facebook link",
      date: "Date",
      addPhotos: "Add photos",
      uploadingPhotos: (done: number, total: number) => `Uploading photo ${done} of ${total}…`,
      removePhoto: "Remove photo",
      movePhotoEarlier: "Move earlier",
      movePhotoLater: "Move later",
      photoCount: (n: number, max: number) => `${n} / ${max} photos`,
      photosFull: "A post can have up to 20 photos.",
      youtubeLabel: "YouTube video link",
      youtubeHelp: "Paste a YouTube video link. The video plays inside the post.",
      facebookLabel: "Facebook post or video link",
      facebookHelp: "Paste the link of a public Facebook post or video. It is shown inside the post.",
      dateLabel: "Post date",
      dateHelp: "Posts are listed newest first by this date. Leave it as it is for today.",
      hide: "Remove",
      post: "Post",
      publishNow: "Publish",
      saveChanges: "Save changes",
      saveDraft: "Save as draft",
      unpublish: "Unpublish",
      working: "Please wait…",
      saved: "Saved.",
      waitForUploads: "Please wait until the photos finish uploading.",
    },
    errors: {
      text: "Write something, or add a photo, video or link.",
      textTooLong: (max: number) => `A post can have up to ${max} characters.`,
      category: "Choose a category before posting.",
      youtube: "Enter a valid YouTube video link (https://youtube.com/watch?v=… or https://youtu.be/…).",
      facebook: "Enter a valid Facebook link (https://facebook.com/…).",
      date: "Enter a valid date.",
      photos: "Some photos are invalid. Please upload them again.",
      tooManyPhotos: "A post can have up to 20 photos.",
      notFound: "That post no longer exists.",
    },
  },
  team: {
    title: "Executive Committee",
    newMember: "Add member",
    editMember: "Edit member",
    empty: "No members in this group yet.",
    moveUp: "Move up",
    moveDown: "Move down",
    confirmDelete: "Remove this member permanently? This cannot be undone.",
    noPhoto: "No photo",
    form: {
      name: "Name",
      nameHelp: "Write it in Tamil, including the title (for example திரு, திருமதி, செல்வி).",
      group: "Group",
      roleTitle: "Role title",
      roleTitleHelp: "Shown under the name, in Tamil. Filled in automatically from the group if left empty.",
      subtitle: "Extra line (optional)",
      subtitleHelp: "For example a profession, shown under the role. Write it in Tamil.",
      photo: "Photo",
      photoHelp: "A clear head-and-shoulders photo works best. It is resized automatically.",
      create: "Add member",
      save: "Save member",
      saved: "Member saved.",
    },
    errors: {
      name: "Enter the member's name.",
      group: "Choose a group.",
      roleTitle: "Enter a role title.",
      photo: "Please upload the photo again.",
      notFound: "That member no longer exists.",
    },
  },
  settings: {
    title: "Settings",
    save: "Save changes",
    saving: "Saving…",
    saved: "Changes saved.",
    fixErrors: "Please fix the highlighted errors and try again.",
    saveFailed: "Could not save. Please try again.",
    tooLong: (n: number) => `Maximum ${n} characters allowed.`,
    errors: {
      email: "Enter a valid email address.",
      phone: "Enter a valid phone number.",
      facebook: "Enter a valid Facebook link (https://facebook.com/…).",
      youtube: "Enter a valid YouTube link (https://youtube.com/…).",
      image: "Please upload the image again.",
    },
  },
  uploader: {
    choose: "Choose image",
    change: "Change image",
    remove: "Remove image",
    uploading: "Uploading…",
    noImage: "No image selected.",
    unsupported: "This image format is not supported. Use a JPG, PNG or WebP image.",
    failed: "Could not upload the image. Please try again.",
    notConfigured: "Photo storage is not set up yet.",
  },
} as const;
